# Generated by Django 5.2.3 on 2025-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rd',
            field=models.FloatField(default=350.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='vol',
            field=models.FloatField(default=0.06),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=1500.0),
        ),
    ]
