# Generated by Django 5.2.3 on 2025-06-19 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_profile_rd_profile_vol_alter_profile_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('ai', 'Contra IA'), ('pvp', 'Jogador vs Jogador')], default='ai', max_length=3),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
