# Generated by Django 5.2.3 on 2025-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_type_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_history',
            field=models.TextField(default='[]'),
        ),
    ]
