# Generated by Django 5.2.3 on 2025-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_move_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='time_control_minutes',
            field=models.IntegerField(default=10, help_text='Tempo inicial em minutos para cada jogador'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='time_increment_seconds',
            field=models.IntegerField(default=0, help_text='Incremento em segundos por lance'),
        ),
        migrations.AddField(
            model_name='game',
            name='black_time_left',
            field=models.IntegerField(blank=True, help_text='Tempo restante das pretas em segundos', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_move_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp do último movimento', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_increment',
            field=models.IntegerField(default=0, help_text='Incremento em segundos por lance'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time_left',
            field=models.IntegerField(blank=True, help_text='Tempo restante das brancas em segundos', null=True),
        ),
    ]
